### PR TITLE
Added new element type: ExternalSignature

### PR DESCRIPTION
**Pull request by jtrein**
From @fforbeck:

It adds a new element type called ExternalSignature, which is an Identity type with a service name used to indicate which service must sign the contract.

🚨 Dependencies: 
1. https://github.com/openlawteam/openlaw-core/pull/165
2. https://github.com/openlawteam/openlaw-client/pull/86

### CODE REVIEW

**Comment by jtrein** [comment]
*I've approved this in the old PR:* https://github.com/openlawteam/openlaw-elements/pull/68

###Reposting feedback:

Looks good! I added only a few small changes to align with another branch I am working in. Just getting ahead.

**Question**

Is it possible to obtain the serviceName separate from the savedValue (e.g. Openlaw.getExternalServiceName(variable))? It may be nice to show the signing serviceName in the UI, especially if the user opts for a generic placeholder, like "Email". The reason I ask is that it suddenly appears when there is a savedValue, but is not present if not.

**Comment by jtrein** [comment]
@jdville03 I can't approve this b/c I opened a new PR. Could you, if you have time, review? Or re-approve the changes?

**Comment by jdville03** [comment]
> Is it possible to obtain the `serviceName` separate from the `savedValue` (e.g. `Openlaw.getExternalServiceName(variable)`)? It may be nice to show the signing `serviceName` in the UI, especially if the user opts for a generic placeholder, like "Email". The reason I ask is that it suddenly appears when there is a `savedValue`, but is not present if not.

Yeah I agree that could be convenient to have.

**Comment by fforbeck** [comment]
@jtrein 
the serviceName is a required field for that variable type, the user has to provide a valid name. Right now we don't have this validation in place, but the idea is to check if the user added a name that matches the services that are registered into Integrators API. If the service name does not match, we would raise an error in the template editor, so we make sure it will always have a valid value to display in the UI.

**Comment by jtrein** [comment]
Thank you, @fforbeck. Makes sense. I’ll create an issue for Elements repo, so I don’t forget about that label.

**Pull request merged**
